namespace ReadMIDI
{
    /// <summary>
    /// Enumeration of the various GM MIDI drums.
    /// </summary>
    public enum MidiDrum : byte
    {
        AcousticBass = 35,
        BassDrum1,
        SideStick,
        AcousticSnare,
        HandClap,
        ElectricSnare,
        LowFloorTom,
        ClosedHiHat,
        HighFloorTom,
        PedalHiHat,
        LowTom,
        OpenHiHat,
        LowMidTom,
        HiMidTom,
        CrashCymbal1,
        HighTom,
        RideCymbal1,
        ChineseCymbal,
        RideBell,
        Tambourine,
        SplashCymbal,
        Cowbell,
        CrashCymbal2,
        Vibraslap,
        RideCymbal2,
        HiBongo,
        LowBongo,
        MuteHiConga,
        OpenHiConga,
        LowConga,
        HighTimbale,
        LowTimbale,
        HighAgogo,
        LowAgogo,
        Cabasa,
        Maracas,
        ShortWhistle,
        LongWhistle,
        ShortGuiro,
        LongGuiro,
        Claves,
        HiWoodBlock,
        LowWoodBlock,
        MuteCuica,
        OpenCuica,
        MuteTriangle,
        OpenTriangle
    }
}
